name: Daily Scraper

on:
  schedule:
    - cron: '0 18 * * *' # Midnight Dhaka Time
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_and_commit:
    runs-on: self-hosted

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Checkout Database (Into the 'public' folder)
      - name: Checkout Database
        uses: actions/checkout@v4
        with:
          ref: database
          path: public

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        shell: powershell
        run: pip install -r scraper/requirements.txt

      - name: Run Scraper
        shell: powershell
        # This will write files into the 'public' folder
        run: node scraper/run.js

      - name: Commit and Push Data
        shell: powershell
        run: |
          # ENTER THE DATABASE BRANCH
          cd public
          
          git config --global user.name "DaamTrack Bot"
          git config --global user.email "bot@daamtrack.bd"
          
          # Add all new files in this branch
          git add .
          
          git diff --staged --quiet
          if ($LASTEXITCODE -ne 0) {
            $today = (Get-Date).ToString("yyyy-MM-dd")
            git commit -m "Daily Update: $today"
            git push
          } else {
            Write-Host "No changes to commit."
          }
